[tool.poetry]
    name        = "bell-avr-vmc-sandbox-module"
    version     = "0.1.0"
    description = "Student autonomy module for Bell AVR"
    license     = "MIT"
    readme      = "README.md"
    homepage    = "https://github.com/bellflight/AVR-VMC-Sandbox-Module"
    authors     = ["Nathan Vaughn <nvaughn51@gmail.com>"]

[tool.poetry.dependencies]
    python                              = ">=3.9,<3.12"
    loguru                              = "^0.6.0"
    bell-avr-libraries                  = { extras = ["mqtt"], version = "^0.1.12" }

[tool.poetry.group.dev.dependencies]
    black            = "^22.10.0"
    isort            = "^5.10.1"
    autoflake        = "^1.7.7"
    pyleft           = "^1.1.0"
    pyproject-flake8 = "^6.0.0.post1"

[tool.pyright]
    typeCheckingMode = "basic"

[tool.isort]
    profile = "black"

[tool.autoflake]
    recursive = true

[tool.flake8]
    exclude = ".venv"
    # E501 is line too long
    # E203 is whitespace before ':'
    # W503 is line break before binary operator
    ignore = "E501, E203, W503"
