name: Build Sandbox Module

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop

jobs:
  checks:
    uses: bellflight/github-actions/.github/workflows/avr_build_and_push_container.yml@main
    with:
      container_name: Sandbox