name: Python Checks

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop

jobs:
  checks:
    uses: bellflight/github-actions/.github/workflows/avr_python_checks.yml@main